project:
  type: website

website:
  title: "The R Stuff"
  navbar:
    left:
      - text: "{{< fa house-user >}} Home"
        href: index.qmd
      - text: "{{< fa laptop-code >}} Blog"
        href: blog.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ravichowdhury88
      - icon: twitter
        href: https://twitter.com/techixir
format:
  html:
    theme: sandstone
    css: styles.css

editor: visual

